# Generated by Django 4.1.7 on 2023-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Professor', max_length=200, verbose_name='Nome')),
                ('nomeAbreviado', models.CharField(help_text='Nome Abreviado do Professor', max_length=50, verbose_name='NomeAbreviado')),
                ('cpf', models.CharField(help_text='CPF do professor', max_length=11, verbose_name='CPF')),
                ('endereco', models.CharField(help_text='Endereço do professor: Rua e Numero', max_length=100, verbose_name='Endereco')),
                ('cidade', models.CharField(help_text='Cidade do professor', max_length=100, verbose_name='Cidade')),
                ('cep', models.CharField(help_text='Cep da cidade do professor', max_length=8, verbose_name='CEP')),
            ],
        ),
    ]
