# Generated by Django 4.1.7 on 2023-05-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronograma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da materia', max_length=200, verbose_name='Nome')),
                ('descricao', models.CharField(help_text='Descreva a materia', max_length=2000, verbose_name='Descricao')),
                ('curso', models.CharField(help_text='Curso da materia', max_length=50, verbose_name='Curso')),
                ('semestre', models.IntegerField(help_text='Numero do semestre que é a materia', verbose_name='Semestre')),
                ('professor', models.ForeignKey(help_text='Materia que o professor ensina', on_delete=django.db.models.deletion.CASCADE, to='Cronograma.professor', verbose_name='Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(help_text='Dia da semana da disciplina', max_length=200, verbose_name='Dia')),
                ('horario', models.CharField(help_text='Horario da disciplina', max_length=5, verbose_name='horario')),
                ('materia', models.ForeignKey(help_text='horario da materia', on_delete=django.db.models.deletion.CASCADE, to='Cronograma.materia', verbose_name='Materia')),
                ('professor', models.ForeignKey(help_text='horario da aula do professor', on_delete=django.db.models.deletion.CASCADE, to='Cronograma.professor', verbose_name='Professor')),
            ],
        ),
    ]
