# Generated by Django 4.1.7 on 2023-05-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronograma', '0004_professor_estado_alter_horario_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='nomeAbreviado',
            new_name='nome_abreviado',
        ),
    ]
